export const GET_INITIAL_STATE = 'GET_INITIAL_STATE';
export const EXPRESSION_APPEND = 'EXPRESSION_APPEND';
export const CALCULATE_EXPRESSION = 'CALCULATE_EXPRESSION';
export const RESET_CALCULATOR = 'RESET_CALCULATOR';
